from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.car_dealership_view, name="car_dealership"),
    path("test/", views.test, name="test"),
    path("test2/", views.test2, name="test2"),
    path("sales_stats/", views.sales_stats, name="sales_stats"),
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("admin-home/", views.admin_home, name="admin_home"),
    path("brand-list/", views.brand_list, name="brand_list"),
    path("model-list/", views.model_list, name="model_list"),
    path("car-list/", views.car_list, name="car_list"),
    path("add-user/", views.add_user, name="add_user"),
    path("add-car-brand/", views.add_car_brand, name="add_car_brand"),
    path("add-car-model/", views.add_car_model, name="add_car_model"),
    path("add-car/", views.add_car, name="add_car"),
    path("delete_selected_brands/", views.delete_selected_brands, name="delete_selected_brands"),
    path("delete_selected_cars/", views.delete_selected_cars, name="delete_selected_cars"),
    path("delete_selected_models/", views.delete_selected_models, name="delete_selected_models"),
    path("delete_selected_users/", views.delete_selected_users, name="delete_selected_users"),
    path("cancel-brand/", views.cancel_brand, name="cancel_brand"),
    path("cancel-model/", views.cancel_model, name="cancel_model"),
    path("cancel-car/", views.cancel_car, name="cancel_car"),
    path("cancel-user/", views.cancel_user, name="cancel_user"),
    path("edit-user/<int:user_id>/", views.edit_user, name="edit_user"),
    path("delete-user/<int:user_id>/", views.delete_user, name="delete_user"),
    path("edit-brand/<int:brand_id>/", views.edit_brand, name="edit_brand"),
    path("delete-brand/<int:brand_id>/", views.delete_brand, name="delete_brand"),
    path("edit-model/<int:model_id>/", views.edit_model, name="edit_model"),
    path("delete-model/<int:model_id>/", views.delete_model, name="delete_model"),
    path("edit-car/<int:car_id>/", views.edit_car, name="edit_car"),
    path("delete-car/<int:car_id>/", views.delete_car, name="delete_car"),
    path('car/<int:car_id>/save_financial_details/', views.save_financial_details, name='save_financial_details'),
    path(
        "brand-<str:brand_name>/model-<str:model_name>/",
        views.car_dealership_view,
        name="car_model_page",
    ),
    path(
        "details/<int:car_id>/",
        views.car_details,
        name="car_details",
    ),
    path("details/<int:car_id>/additional-images/", views.additional_images, name="additional_images"),
    path('upload_legal_documents/<int:car_id>/', views.upload_legal_documents, name='upload_legal_documents'),
    path('display_legal_documents/<int:car_id>/', views.display_legal_documents, name='display_legal_documents'),
    path('clear_legal_documents/<int:car_id>/', views.clear_legal_documents, name='clear_legal_documents'),
]
