# Generated by Django 4.2.6 on 2023-11-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nissan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toyota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='CarBrand',
            new_name='Honda',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='car',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
