# Generated by Django 4.2.3 on 2023-11-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_car_carmodel_customer_sale_delete_nissan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='car',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='car',
            name='image_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
