# Generated by Django 4.2.3 on 2023-11-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0004_remove_sale_car_remove_sale_customer_car_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image_path',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
