# Generated by Django 4.2.3 on 2023-11-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
