# Generated by Django 4.2.3 on 2023-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0008_car_color_car_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='optional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
