# Generated by Django 4.2.3 on 2023-11-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0009_car_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
