# Generated by Django 4.2.3 on 2023-11-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0011_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
