# Generated by Django 4.2.3 on 2023-11-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0013_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
