# Generated by Django 4.2.3 on 2023-11-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0016_remove_carimage_car_car_images_alter_carimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='car_dealership.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='car_dealership.carimage'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
