# Generated by Django 4.2.3 on 2023-12-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0028_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='Additional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='CO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='Particulars',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
