# Generated by Django 4.2.3 on 2023-12-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0029_finance_car_alter_finance_additional_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
