# Generated by Django 4.2.3 on 2023-12-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0031_finance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='car',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='co',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='particulars',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='total',
        ),
        migrations.CreateModel(
            name='FinanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(choices=[('BUY', 'Buy'), ('REPAIRS', 'Repairs'), ('SOLD', 'Sold'), ('BROKAGE', 'Brokage')], max_length=8)),
                ('co', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('additional', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.finance')),
            ],
        ),
    ]
