# Generated by Django 4.2.3 on 2023-12-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0034_remove_financedetail_finance_alter_finance_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='car',
        ),
        migrations.DeleteModel(
            name='FinanceDetail',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
