# Generated by Django 4.2.3 on 2023-12-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0036_financialdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdetails',
            name='brokage_additional',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='brokage_amount',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='brokage_co',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='brokage_total',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='repairs_additional',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='repairs_amount',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='repairs_co',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='repairs_total',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='sold_additional',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='sold_amount',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='sold_co',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='sold_total',
        ),
    ]
