# Generated by Django 4.2.3 on 2023-12-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0038_financialdetails_repair_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdetails',
            name='brokage_additional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='brokage_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='brokage_co',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='brokage_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='sold_additional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='sold_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='sold_co',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='sold_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
