# Generated by Django 4.2.3 on 2023-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0039_financialdetails_brokage_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdetails',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='profit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
