# Generated by Django 4.2.3 on 2023-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0040_financialdetails_note_financialdetails_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcarimage',
            name='legal_documents',
            field=models.ImageField(blank=True, null=True, upload_to='legal_documents/'),
        ),
    ]
