# Generated by Django 4.2.3 on 2023-12-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0042_remove_additionalcarimage_legal_documents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocuments',
        ),
    ]
