# Generated by Django 4.2.3 on 2023-12-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0044_legaldocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
