# Generated by Django 4.2.3 on 2023-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0046_legaldocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdetails',
            name='legal_documents',
            field=models.ImageField(blank=True, null=True, upload_to='legal_documents/'),
        ),
        migrations.DeleteModel(
            name='LegalDocuments',
        ),
    ]
