# Generated by Django 4.2.3 on 2023-12-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0048_remove_financialdetails_legal_documents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaldocument',
            old_name='legal_documents',
            new_name='legal_document',
        ),
    ]
