# Generated by Django 4.2.3 on 2023-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0049_rename_legal_documents_legaldocument_legal_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdetails',
            name='legal_documents',
            field=models.ManyToManyField(blank=True, related_name='financial_details', to='car_dealership.legaldocument'),
        ),
    ]
