# Generated by Django 4.2.3 on 2023-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0050_financialdetails_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seater',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
